// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PingPongService.proto

package com.example.grpc.client.grpcclient.protobuf.java.com.example.grpc.client.grpcclient;

public interface PongResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.PongResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pong = 1;</code>
   */
  java.lang.String getPong();
  /**
   * <code>string pong = 1;</code>
   */
  com.google.protobuf.ByteString
      getPongBytes();
}
